apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulutbilisim-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bulutbilisim
  template:
    metadata:
      labels:
        app: bulutbilisim
    spec:
      containers:
      - name: bulutbilisim-container
        image: ahmetdurgut/bulutbilisim:v2
        ports:
        - containerPort: 5000